# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lark < Formula
  desc "A Go CLI for Feishu/Lark inspired by gog"
  homepage "https://github.com/rintays/lark-cli"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rintays/lark-cli/releases/download/v0.1.8/lark_0.1.8_darwin_amd64.tar.gz"
      sha256 "506b6827761ae638447e8a8097c8c25007e1fca24231fffef176e3927f864a40"

      def install
        bin.install "lark"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rintays/lark-cli/releases/download/v0.1.8/lark_0.1.8_darwin_arm64.tar.gz"
      sha256 "5cd438490c78accfb7cdf2b4cd22b96c4ba12064cebaa646b7a9ed3741c5cf38"

      def install
        bin.install "lark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rintays/lark-cli/releases/download/v0.1.8/lark_0.1.8_linux_amd64.tar.gz"
      sha256 "fd295864e9e531331ac2a68687627560fed5cdd17ddb605480f3d94b6628fe60"
      def install
        bin.install "lark"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rintays/lark-cli/releases/download/v0.1.8/lark_0.1.8_linux_arm64.tar.gz"
      sha256 "57b4ee79555da286bc06e6bc9203326d2d58a3a0b7d3c83502b459676f88742d"
      def install
        bin.install "lark"
      end
    end
  end

  test do
    system "#{bin}/lark", "version"
  end
end
