# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lark < Formula
  desc "A Go CLI for Feishu/Lark inspired by gog"
  homepage "https://github.com/rintays/lark-cli"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rintays/lark-cli/releases/download/v0.1.12/lark_0.1.12_darwin_amd64.tar.gz"
      sha256 "993bc9340edc6d3c0609c64bdbcb2e0ff621e6eb14fea7c6045d965d0c291626"

      def install
        bin.install "lark"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rintays/lark-cli/releases/download/v0.1.12/lark_0.1.12_darwin_arm64.tar.gz"
      sha256 "5e3202b47f3b66e6596dd1a91b3dab611c39d5f0b8f6d3075f4d408db4ff350c"

      def install
        bin.install "lark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rintays/lark-cli/releases/download/v0.1.12/lark_0.1.12_linux_amd64.tar.gz"
      sha256 "c4bd3318c72b08b7aaa4669c3238a00b8d8daed78b1b9a36baf1fb4db6c286af"
      def install
        bin.install "lark"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rintays/lark-cli/releases/download/v0.1.12/lark_0.1.12_linux_arm64.tar.gz"
      sha256 "7a57f3d61cf853b585b5e8230f1d0a98a5f219f8d134f51a13265adc161a1939"
      def install
        bin.install "lark"
      end
    end
  end

  test do
    system "#{bin}/lark", "version"
  end
end
